driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: ubuntu/xenial64

suites:
- name: default
  run_list:
  - recipe[bosh-jumpbox::default]
