---
provisioner:
  name: chef_zero

driver:
  name: docker

platforms:
- name: ubuntu-16.04
  driver:
    image: ubuntu:xenial
    platform: ubuntu
    privileged: true
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
      - adduser ubuntu
      - gpasswd -a ubuntu sudo

suites:
- name: default
  run_list: bosh-jumpbox::default
